# Generated by Django 4.0.2 on 2022-03-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journaly', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
    ]
